from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(
        template_name="web/login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("", views.dashboard, name="dashboard"),
    path("search/", views.global_search, name="global_search"),
    path("changelog/", views.changelog, name="changelog"),
    path("settings/system-status/", views.system_status, name="system_status"),
    path("checkdesk/", views.checkdesk, name="checkdesk"),
    path("checkdesk/action/", views.check_action, name="check_action"),

    path("applications/", views.application_list, name="application_list"),
    path("applications/new/", views.application_form, name="application_new"),
    path("applications/<uuid:pk>/edit/", views.application_form, name="application_edit"),
    path("applications/<uuid:pk>/accept/", views.application_accept, name="application_accept"),
    path("enrollment/<uuid:pk>/end/", views.enrollment_end, name="enrollment_end"),
    path("enrollment/<uuid:pk>/pause/", views.enrollment_pause, name="enrollment_pause"),
    path("enrollment/<uuid:pk>/transfer/", views.enrollment_transfer,
         name="enrollment_transfer"),

    path("groups/", views.group_list, name="group_list"),
    path("groups/new/", views.group_form, name="group_new"),
    path("groups/<uuid:pk>/edit/", views.group_form, name="group_edit"),
    path("groups/<uuid:pk>/", views.group_detail, name="group_detail"),
    path("groups/<uuid:pk>/attendance/", views.attendance_view, name="attendance"),
    path("groups/<uuid:pk>/tabel/", views.tabel_view, name="tabel"),
    path("groups/<uuid:pk>/tabel/lock/", views.month_lock, name="month_lock"),
    path("groups/<uuid:pk>/tabel/unlock/", views.month_unlock, name="month_unlock"),

    path("children/", views.child_list, name="child_list"),
    path("children/new/", views.child_form, name="child_new"),
    path("children/<uuid:pk>/edit/", views.child_form, name="child_edit"),
    path("children/<uuid:child_pk>/contacts/new/", views.contact_form, name="contact_new"),
    path("children/<uuid:child_pk>/contacts/<uuid:pk>/edit/", views.contact_form,
         name="contact_edit"),
    path("children/<uuid:child_pk>/contacts/<uuid:pk>/delete/", views.contact_delete,
         name="contact_delete"),
    path("children/<uuid:child_pk>/contacts/<uuid:contact_pk>/telegram/",
         views.telegram_link, name="telegram_link"),
    path("children/<uuid:pk>/", views.child_detail, name="child_detail"),
    path("children/<uuid:child_pk>/documents/new/", views.child_document_upload,
         name="child_document_upload"),
    path("documents/<uuid:pk>/download/", views.child_document_download,
         name="child_document_download"),
    path("documents/<uuid:pk>/archive/", views.child_document_archive,
         name="child_document_archive"),
    path("children/<uuid:pk>/qr/", views.child_qr, name="child_qr"),
    path("children/<uuid:pk>/enroll/", views.enrollment_form, name="enroll"),

    path("payments/", views.invoice_list, name="invoice_list"),
    path("payments/generate/", views.generate_invoices_view, name="generate_invoices"),
    path("payments/received/", views.payment_list, name="payment_list"),
    path("payments/received/new/", views.payment_form, name="payment_new"),
    path("payments/debts/", views.debt_list, name="debt_list"),
    path("invoice/<uuid:pk>/", views.invoice_detail, name="invoice_detail"),
    path("invoice/<uuid:pk>/pdf/", views.invoice_document, name="invoice_pdf"),
    path("invoice/<uuid:pk>/void/", views.invoice_void, name="invoice_void"),
    path("invoice/<uuid:pk>/line/", views.invoice_add_line, name="invoice_add_line"),
    path("payments/received/<uuid:pk>/reverse/", views.payment_reverse,
         name="payment_reverse"),
    path("payments/received/<uuid:pk>/receipt/", views.payment_receipt,
         name="payment_receipt"),
    path("enrollment/<uuid:pk>/contract/", views.enrollment_contract,
         name="enrollment_contract"),
    path("children/<uuid:pk>/debt-statement/", views.child_debt_statement,
         name="child_debt_statement"),

    path("reports/", views.reports, name="reports"),

    path("settings/", views.settings_view, name="settings"),
    path("settings/tariffs/new/", views.tariff_form, name="tariff_new"),
    path("settings/discounts/new/", views.discount_form, name="discount_new"),
    path("settings/users/", views.user_list, name="user_list"),
    path("settings/users/new/", views.user_form, name="user_new"),
    path("settings/users/<uuid:pk>/edit/", views.user_edit, name="user_edit"),
    path("settings/users/<uuid:pk>/password/", views.user_password_reset,
         name="user_password_reset"),
    path("settings/users/<uuid:pk>/toggle/", views.user_toggle_active,
         name="user_toggle_active"),
    path("settings/users/<uuid:pk>/sessions/", views.user_terminate_sessions,
         name="user_terminate_sessions"),
    path("settings/users/<uuid:pk>/telegram/unlink/", views.user_unlink_telegram,
         name="user_unlink_telegram"),
    path("settings/account/password/", views.own_password_change,
         name="own_password_change"),
    path("settings/users/<uuid:pk>/telegram/", views.staff_telegram_link,
         name="staff_telegram_link"),
    path("settings/roles/new/", views.role_form, name="role_new"),
    path("settings/roles/<uuid:pk>/edit/", views.role_form, name="role_edit"),
    path("settings/roles/<uuid:pk>/delete/", views.role_delete, name="role_delete"),
    path("settings/calendar/", views.calendar_view, name="calendar"),
    path("settings/audit/", views.audit_list, name="audit_list"),
    path("settings/persons/", views.person_list, name="person_list"),
    path("settings/persons/<uuid:source_pk>/merge/", views.person_merge,
         name="person_merge"),
]
