# Generated by Django 5.2.17 on 2026-08-13 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('period', models.DateField(help_text='Oyning birinchi kuni')),
                ('issued_at', models.DateField()),
                ('due_at', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('issued', 'Chiqarilgan'), ('partial', "Qisman to'langan"), ('paid', "To'langan"), ('void', 'Bekor qilingan')], default='issued', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='school.enrollment')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.kindergarten')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('tuition', "Oylik to'lov"), ('proration', 'Qisman oy'), ('hold', 'Joy saqlash'), ('discount', 'Chegirma'), ('manual', "Qo'lda tuzatish")], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('transfer', "Bank o'tkazmasi")], default='cash', max_length=10, verbose_name="To'lov usuli")),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('received_at', models.DateTimeField(verbose_name='Qabul qilindi')),
                ('is_reversed', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='school.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.kindergarten')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['kindergarten', 'period'], name='billing_inv_kinderg_c84382_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('enrollment', 'period')},
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('method', 'external_id'), name='uniq_provider_txn'),
        ),
    ]
