# Generated by Django 5.2.17 on 2026-09-15 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0020_childdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('closed', 'Yopilgan')], default='draft', max_length=10)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fact_entered_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_menus', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_menus', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('meal_type', models.CharField(choices=[('nonushta', 'Nonushta'), ('tushlik', 'Tushlik'), ('gazak', 'Gazak'), ('kechki', 'Kechki ovqat')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='school.kindergarten')),
            ],
            options={
                'ordering': ['meal_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('sabzavot', 'Sabzavot'), ('meva', 'Meva'), ('gosht', "Go'sht"), ('sut', 'Sut mahsuloti'), ('don', 'Don mahsuloti'), ('yog', "Yog'"), ('ziravor', 'Ziravor'), ('boshqa', 'Boshqa')], max_length=20)),
                ('display_unit', models.CharField(choices=[('kg', 'kg'), ('litr', 'litr'), ('dona', 'dona')], default='kg', max_length=10)),
                ('gram_per_piece', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stock_g', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='school.kindergarten')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grams_per_child', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='kitchen.dish')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_norms', to='kitchen.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='MenuDish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('nonushta', 'Nonushta'), ('tushlik', 'Tushlik'), ('gazak', 'Gazak'), ('kechki', 'Kechki ovqat')], max_length=12)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_entries', to='kitchen.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='kitchen.dailymenu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_g', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_g', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_lines', to='kitchen.ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='kitchen.dailymenu')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_suppliers', to='school.kindergarten')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim')], max_length=3)),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('happened_at', models.DateField()),
                ('document_number', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(default='manual', max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='kitchen.ingredient')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='school.kindergarten')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='kitchen.stockmove')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='kitchen.supplier')),
            ],
            options={
                'ordering': ['-happened_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailymenu',
            index=models.Index(fields=['kindergarten', 'date'], name='kitchen_dai_kinderg_113f90_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailymenu',
            constraint=models.UniqueConstraint(fields=('kindergarten', 'date'), name='kitchen_unique_daily_menu'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(fields=('kindergarten', 'name'), name='kitchen_unique_dish'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('kindergarten', 'name'), name='kitchen_unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock_g__gte', 0)), name='kitchen_min_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.UniqueConstraint(fields=('dish', 'ingredient'), name='kitchen_unique_dish_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='dishingredient',
            constraint=models.CheckConstraint(condition=models.Q(('grams_per_child__gt', 0)), name='kitchen_norm_positive'),
        ),
        migrations.AddConstraint(
            model_name='menudish',
            constraint=models.UniqueConstraint(fields=('menu', 'dish'), name='kitchen_unique_menu_dish'),
        ),
        migrations.AddConstraint(
            model_name='menuline',
            constraint=models.UniqueConstraint(fields=('menu', 'ingredient'), name='kitchen_unique_menu_line'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('kindergarten', 'name'), name='kitchen_unique_supplier'),
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['kindergarten', 'ingredient', 'happened_at'], name='kitchen_sto_kinderg_964c1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmove',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_g__gt', 0)), name='kitchen_move_quantity_positive'),
        ),
    ]
