# Generated by Django 5.2.17 on 2026-08-13 12:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='Nomi')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Foiz')),
                ('is_active', models.BooleanField(default=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='school.kindergarten')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160, verbose_name='F.I.O.')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('parent_name', models.CharField(max_length=160, verbose_name='Ota-ona')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('parent_phone_2', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='school.kindergarten')),
            ],
            options={
                'verbose_name_plural': 'Bolalar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_proration', models.CharField(choices=[('daily', "Kunlar bo'yicha"), ('half', 'Yarim oy'), ('full', "To'liq oy")], default='daily', max_length=10, verbose_name="Oy o'rtasida kirish")),
                ('exit_proration', models.CharField(choices=[('daily', "Kunlar bo'yicha"), ('half', 'Yarim oy'), ('full', "To'liq oy")], default='daily', max_length=10, verbose_name="Oy o'rtasida chiqish")),
                ('absent_month_mode', models.CharField(choices=[('full', "To'liq olinadi"), ('percent', 'Foiz bilan (joy saqlash)'), ('none', 'Olinmaydi')], default='full', max_length=10, verbose_name='Butun oy kelmasa')),
                ('absent_month_percent', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Joy saqlash foizi')),
                ('absent_month_threshold', models.PositiveSmallIntegerField(default=0, help_text="Necha kundan kam kelsa 'butun oy kelmadi' hisoblanadi.", verbose_name='Chegara (kun)')),
                ('invoice_generation_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Invoys chiqadigan kun')),
                ('due_day', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name="To'lov muddati (kun)")),
                ('overpayment_as_advance', models.BooleanField(default=True, verbose_name="Ortiqcha to'lov avansda")),
                ('rounding_step', models.PositiveIntegerField(default=100, verbose_name='Yaxlitlash qadami')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('kindergarten', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='school.kindergarten')),
            ],
            options={
                'verbose_name': 'Moliyaviy siyosat',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oylik summa')),
                ('valid_from', models.DateField(verbose_name='Amal qiladi')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Tugaydi')),
                ('is_active', models.BooleanField(default=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Nomi')),
                ('age_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yosh (dan)')),
                ('age_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yosh (gacha)')),
                ('capacity', models.PositiveSmallIntegerField(default=25, verbose_name="Sig'im")),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups', to=settings.AUTH_USER_MODEL, verbose_name='Tarbiyachi')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='school.kindergarten')),
                ('default_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.tariff', verbose_name='Standart tarif')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateField(verbose_name='Boshlanish')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Tugash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school.child')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.discount', verbose_name='Chegirma')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school.group')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.tariff', verbose_name='Tarif')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['group', 'ended_at'], name='school_enro_group_i_0a0b88_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('is_working', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_days', to='school.kindergarten')),
            ],
            options={
                'ordering': ['day'],
                'indexes': [models.Index(fields=['kindergarten', 'day'], name='school_work_kinderg_04b95d_idx')],
                'unique_together': {('kindergarten', 'day')},
            },
        ),
    ]
