# Generated by Django 5.2.17 on 2026-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'permissions': [('view_all_groups', "Barcha guruhlarni ko'rish")]},
        ),
    ]
