# Generated by Django 5.2.17 on 2026-08-15 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('graduated', 'Bitirdi'), ('left', 'Ketdi'), ('transferred', "Boshqa bog'chaga o'tdi"), ('expelled', 'Chiqarildi')], max_length=12, verbose_name='Tugash sababi'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paused',
            field=models.BooleanField(default=False, help_text="Yoqilgan bo'lsa invoys chiqmaydi. Joy saqlanadi.", verbose_name="Vaqtincha to'xtatilgan"),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pause_note',
            field=models.CharField(blank=True, max_length=200, verbose_name="To'xtatish sababi"),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=160, verbose_name='Bola F.I.O.')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('parent_name', models.CharField(max_length=160, verbose_name='Ota-ona')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('desired_start', models.DateField(blank=True, null=True, verbose_name='Boshlash sanasi')),
                ('status', models.CharField(choices=[('inquiry', "So'rov"), ('toured', 'Tanishuvga keldi'), ('applied', 'Ariza topshirdi'), ('waitlist', 'Navbatda'), ('accepted', 'Qabul qilindi'), ('declined', 'Rad etildi'), ('lost', 'Boshqa joyni tanladi')], default='inquiry', max_length=10, verbose_name='Holat')),
                ('source', models.CharField(blank=True, help_text="Tavsiya, Instagram, yon ko'chadan va h.k.", max_length=80, verbose_name='Qayerdan bilgan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, help_text="Qabul qilingandan keyin to'ldiriladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='school.child')),
                ('desired_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group', verbose_name='Istalgan guruh')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kindergarten', 'status'], name='school_appl_kinderg_628be6_idx')],
            },
        ),
    ]
