# Generated by Django 5.2.17 on 2026-08-16 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_enrollment_end_reason_enrollment_is_paused_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text="Tarbiyachi va yordamchi. Faqat shu ro'yxatdagilar guruh davomatini belgilay oladi.", related_name='taught_groups', to=settings.AUTH_USER_MODEL, verbose_name='Tarbiyachilar'),
        ),
    ]
