# Generated by Django 5.2.17 on 2026-08-16 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_group_teacher_group_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='closes_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish tugashi'),
        ),
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz'), ('mixed', 'Aralash')], default='uz', max_length=6, verbose_name="Ta'lim tili"),
        ),
        migrations.AddField(
            model_name='group',
            name='lead_teacher',
            field=models.ForeignKey(blank=True, help_text="Tarbiyachilar ro'yxatidan bittasi. Hisobot va mas'uliyat uchun.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_groups', to=settings.AUTH_USER_MODEL, verbose_name='Asosiy tarbiyachi'),
        ),
        migrations.AddField(
            model_name='group',
            name='opens_at',
            field=models.TimeField(blank=True, null=True, verbose_name='Ish boshlanishi'),
        ),
        migrations.AddField(
            model_name='group',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Xona raqami'),
        ),
    ]
