# Generated by Django 5.2.17 on 2026-08-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_group_closes_at_group_language_group_lead_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_ratio',
            field=models.PositiveSmallIntegerField(default=0, help_text="0 = tekshirilmaydi. Masalan 10 = bitta tarbiyachiga 10 tadan ko'p bola bo'lmasligi kerak.", verbose_name='Maksimal nisbat (bola : tarbiyachi)'),
        ),
    ]
