# Generated by Django 5.2.17 on 2026-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_group_max_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='allergies',
            field=models.CharField(blank=True, help_text="Bola kartasida qizil ogohlantirish sifatida ko'rinadi.", max_length=200, verbose_name='Allergiya'),
        ),
        migrations.AddField(
            model_name='child',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text="Bo'sh qoldirilsa avtomatik beriladi.", max_length=20, verbose_name='ID raqami'),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Favqulodda aloqa (ism)'),
        ),
        migrations.AddField(
            model_name='child',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Favqulodda aloqa (telefon)'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', "O'g'il"), ('f', 'Qiz')], max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='child',
            name='health_note',
            field=models.TextField(blank=True, help_text='Surunkali kasallik, doimiy dori, cheklovlar.', verbose_name="Sog'liq haqida"),
        ),
    ]
