# Generated by Django 5.2.17 on 2026-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_child_allergies_child_code_child_emergency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='child',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Shifokor'),
        ),
        migrations.AddField(
            model_name='child',
            name='doctor_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Shifokor telefoni'),
        ),
    ]
