# Generated by Django 5.2.17 on 2026-08-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_remove_child_legacy_contacts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='school_cont_child_i_413e52_idx',
            old_name='school_cont_child_i_2d07d0_idx',
        ),
    ]
