# Generated by Django 5.2.17 on 2026-08-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_school_cont_child_i_2d07d0_idx_school_cont_child_i_413e52_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='school.group', verbose_name='Guruh'),
        ),
    ]
