# Generated by Django 5.2.17 on 2026-08-22 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_enrollment_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('age_from__isnull', True), ('age_to__isnull', True), ('age_from__lte', models.F('age_to')), _connector='OR'), name='group_valid_age_range'),
        ),
    ]
