# Generated by Django 5.2.17 on 2026-08-24 14:49

import uuid
from django.db import migrations, models


def fill_unique_tokens(apps, schema_editor):
    Child = apps.get_model('school', 'Child')
    for child in Child.objects.filter(check_token__isnull=True).iterator():
        child.check_token = uuid.uuid4()
        child.save(update_fields=['check_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_group_group_valid_age_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='check_token',
            field=models.UUIDField(editable=False, null=True, verbose_name='Check-in QR tokeni'),
        ),
        migrations.RunPython(fill_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='child',
            name='check_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Check-in QR tokeni'),
        ),
    ]
