# Generated by Django 5.2.17 on 2026-08-24 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_child_check_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notify_attendance',
            field=models.BooleanField(default=True, verbose_name='Davomat xabarlari'),
        ),
        migrations.AddField(
            model_name='contact',
            name='notify_billing',
            field=models.BooleanField(default=True, verbose_name='Moliya xabarlari'),
        ),
        migrations.CreateModel(
            name='PickupPass',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_passes', to='school.child')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_passes', to='school.contact')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField()),
                ('language', models.CharField(default='uz', max_length=2)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='telegram_accounts', to='school.contact')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramLinkCode',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_codes', to='school.contact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
