# Generated by Django 5.2.17 on 2026-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_contactpass_stafftelegramaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='bank_account',
            field=models.CharField(blank=True, max_length=32, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='bank_mfo',
            field=models.CharField(blank=True, max_length=10, verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='bank_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Bank nomi'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='director_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Direktor F.I.O.'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='STIR'),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rasmiy nomi'),
        ),
    ]
