# Generated by Django 5.2.17 on 2026-08-30 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0018_kindergarten_bank_account_kindergarten_bank_mfo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Xabar')),
                ('send_at', models.DateTimeField(verbose_name='Yuborish vaqti')),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-send_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('food', 'Oziq-ovqat'), ('rent', 'Ijara'), ('utilities', 'Kommunal'), ('household', "Xo'jalik"), ('salary', 'Ish haqi'), ('education', "Ta'lim xarajati"), ('other', 'Boshqa')], max_length=16, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='school.kindergarten')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'unique_together': {('kindergarten', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Oylik maosh')),
                ('effective_from', models.DateField(verbose_name='Amal qilish sanasi')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, verbose_name='Nomi')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='STIR')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('bank_account', models.CharField(blank=True, max_length=32, verbose_name='Hisob raqami')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='school.kindergarten')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('kindergarten', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopilgan')], default='open', max_length=8)),
                ('close_note', models.CharField(blank=True, max_length=200)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-opened_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('kindergarten',), name='one_open_cash_shift_per_kg')],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('kind', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='school.kindergarten')),
            ],
            options={
                'ordering': ['available_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='operations__status_2e0e7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(verbose_name='Davr')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Asosiy maosh')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Avans')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bonus')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Jarima')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('approved', 'Tasdiqlangan'), ('paid', "To'langan")], default='draft', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_entries', to='school.kindergarten')),
            ],
            options={
                'ordering': ['-period', 'employee__full_name'],
                'unique_together': {('kindergarten', 'employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180, verbose_name='Xarajat nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Summa')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazmasi")], max_length=12, verbose_name="To'lov usuli")),
                ('paid_at', models.DateTimeField(verbose_name="To'langan vaqt")),
                ('document_number', models.CharField(blank=True, max_length=80, verbose_name='Hujjat raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_void', models.BooleanField(default=False, verbose_name='Bekor qilingan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='school.group', verbose_name='Guruh')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='school.kindergarten')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operations.expensecategory', verbose_name='Kategoriya')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='operations.supplier', verbose_name='Yetkazib beruvchi')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['kindergarten', 'paid_at'], name='operations__kinderg_b3f86d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive')],
            },
        ),
    ]
