# Generated by Django 5.2.17 on 2026-08-30 10:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_seed_categories'),
        ('school', '0018_kindergarten_bank_account_kindergarten_bank_mfo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshift',
            name='actual_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cashshift',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Avans'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asosiy maosh'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jarima'),
        ),
        migrations.AddConstraint(
            model_name='cashshift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='cash_shift_opening_nonnegative'),
        ),
    ]
