# Generated by Django 5.2.17 on 2026-08-13 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('sick', 'Kasal'), ('family', 'Oilaviy'), ('vacation', "Ta'til"), ('unexcused', 'Sababsiz')], max_length=12)),
                ('arrived_at', models.TimeField(blank=True, null=True)),
                ('left_at', models.TimeField(blank=True, null=True)),
                ('has_document', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='school.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['enrollment', 'day'], name='attendance__enrollm_81b52e_idx')],
                'unique_together': {('enrollment', 'day')},
            },
        ),
        migrations.CreateModel(
            name='MonthLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='Oyning birinchi kuni')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_note', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_locks', to='school.group')),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'period')},
            },
        ),
    ]
