# Generated by Django 5.2.17 on 2026-08-24 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('school', '0015_child_check_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('in', 'Check-in'), ('out', 'Check-out')], max_length=4)),
                ('occurred_at', models.DateTimeField()),
                ('method', models.CharField(choices=[('qr', 'QR'), ('manual', "Qo'lda"), ('parent_pass', 'Ota-ona QR')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_events', to='school.enrollment')),
                ('pickup_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_events', to='school.contact', verbose_name='Olib ketuvchi')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'permissions': [('check_in_child', 'Bolani check-in qilish'), ('check_out_child', 'Bolani check-out qilish'), ('manual_check_child', "Qo'lda check-in/out qilish")],
                'indexes': [models.Index(fields=['enrollment', 'occurred_at'], name='attendance__enrollm_515f5e_idx')],
            },
        ),
    ]
