# Generated by Django 5.2.17 on 2026-08-25 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_checkevent'),
        ('school', '0017_contactpass_stafftelegramaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkevent',
            options={'ordering': ['-occurred_at'], 'permissions': [('check_in_child', 'Bolani check-in qilish'), ('check_out_child', 'Bolani check-out qilish'), ('manual_check_child', "Qo'lda check-in/out qilish"), ('override_check_child', 'Ruxsatsiz check-outni tasdiqlash')]},
        ),
        migrations.AddField(
            model_name='checkevent',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_events', to='school.contact', verbose_name='Topshirgan/olib ketgan kontakt'),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='device_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='idempotency_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overridden_check_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='override_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='checkevent',
            name='synced_offline',
            field=models.BooleanField(default=False),
        ),
    ]
